[package]
name = "raytracer"
version = "0.1.0"
authors = ["Stepan Khodzhaian <mightykho.dev@gmail.com>"]

[dependencies]
rand = "0.5"
image = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
scoped_threadpool = "0.1.*"
num_cpus = "1.0"
