[package]
name = "app"
version = "0.1.0"
authors = ["Stepan Khodzhaian <mightykho.dev@gmail.com>"]

[dependencies]
raytracer = { path = ".." }
clap = {version = "~2.27.0", features = ["yaml"]}
image = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
